version: "3.9"

services:
  app:
    build: .
    container_name: devsecops_app

    ports:
      - "5000:5000"
      
    environment:
      - APP_NAME=DevSecOps Mini Platform
      - APP_VERSION=0.1.0
      - APP_ENV=development
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000

    volumes:
      - .:/app

    restart: unless-stopped